<?php

namespace DOH\InfraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FarmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FarmRepository extends EntityRepository
{
}
