<?php

namespace DOH\InfraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServerChangelogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerChangelogRepository extends EntityRepository
{
}
