<?php

namespace DOH\GuideBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GuideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuideRepository extends EntityRepository
{

}
