doh_main_user:
    resource: "routing.user.yml"
    prefix:   /

doh_main_dashboard:
    path:     /
    defaults: { _controller: DOHMainBundle:Default:index }

doh_main_about:
    path:     /about
    defaults: { _controller: DOHMainBundle:Default:about }
