parameters:
  doh_main.keyboard_control.handler.class:   DOH\MainBundle\KeyboardControl\KeyboardControlHandler
  doh_main.keyboard_control_extension.class: DOH\MainBundle\DependencyInjection\KeyboardControlExtension

services:
  doh_main.keyboard_control.handler:
    class: %doh_main.keyboard_control.handler.class%

  doh_main.keyboard_control_extension:
    class: %doh_main.keyboard_control_extension.class%
    tags:
      - { name: doh_main.keyboard_control.extension }
