parameters:
#    doh_main.example.class: DOH\MainBundle\Example

services:
#    doh_main.example:
#        class: %doh_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
