parameters:

  doh_infra.form.type.server.class:                DOH\InfraBundle\Form\ServerType
  doh_infra.form.type.server_spec_sheet.class:     DOH\InfraBundle\Form\Type\ServerSpecSheetType
  doh_infra.form.type.server_disk_partition.class: DOH\InfraBundle\Form\Type\DiskPartitionType
  doh_infra.form.type.server_nic.class:            DOH\InfraBundle\Form\Type\NicType
  doh_infra.form.type.server_changelog.class:      DOH\InfraBundle\Form\ChangelogType
  doh_infra.keyboard_control_extension.class:      DOH\InfraBundle\DependencyInjection\KeyboardControlExtension
  doh_infra.form.type.farm.class:                  DOH\InfraBundle\Form\FarmType
  doh_infra.form.type.role.class:                  DOH\InfraBundle\Form\RoleType
  doh_infra.menu_provider.class:                   DOH\InfraBundle\DependencyInjection\MenuProvider

services:

  doh_infra.form.type.server:
    class: %doh_infra.form.type.server.class%
    tags:
      - { name: form.type, alias: doh_infra_server }

  doh_infra.form.type.server_spec_sheet:
    class: %doh_infra.form.type.server_spec_sheet.class%
    tags:
      - { name: form.type, alias: doh_infra_server_spec_sheet }

  doh_infra.form.type.server_disk_partition:
    class: %doh_infra.form.type.server_disk_partition.class%
    tags:
      - { name: form.type, alias: doh_infra_server_disk_partition }

  doh_infra.form.type.server_nic:
    class: %doh_infra.form.type.server_nic.class%
    tags:
      - { name: form.type, alias: doh_infra_server_nic }

  doh_infra.form.type.server_changelog:
    class: %doh_infra.form.type.server_changelog.class%
    calls:
      - [setRequest, [@request]]
      - [setGuideRepository, [@doh_guide.repo.guide]]
    public: true
    scope: request
    tags:
      - { name: form.type, alias: doh_infra_server_changelog }

  doh_infra.keyboard_control_extension:
    class: %doh_infra.keyboard_control_extension.class%
    arguments: [@router]
    tags:
      - { name: doh_main.keyboard_control.extension }

  doh_infra.form.type.farm:
    class: %doh_infra.form.type.farm.class%
    tags:
      - { name: form.type, alias: doh_infra_farm }

  doh_infra.form.type.role:
    class: %doh_infra.form.type.role.class%
    tags:
      - { name: form.type, alias: doh_infra_role }

  doh_infra.menu_provider:
    class: %doh_infra.menu_provider.class%
    tags:
      - { name: doh_main.menu.provider }
