parameters:

  doh_infra.form.type.server.class:                DOH\InfraBundle\Form\Type\ServerType
  doh_infra.form.type.server_spec_sheet.class:     DOH\InfraBundle\Form\Type\ServerSpecSheetType
  doh_infra.form.type.server_disk_partition.class: DOH\InfraBundle\Form\Type\DiskPartitionType

services:

  doh_infra.form.type.server:
    class: %doh_infra.form.type.server.class%
    tags:
      - { name: form.type, alias: doh_infra_server }

  doh_infra.form.type.server_spec_sheet:
    class: %doh_infra.form.type.server_spec_sheet.class%
    tags:
      - { name: form.type, alias: doh_infra_server_spec_sheet }

  doh_infra.form.type.server_disk_partition:
    class: %doh_infra.form.type.server_disk_partition.class%
    tags:
      - { name: form.type, alias: doh_infra_server_disk_partition }
