parameters:

  doh_infra.form.type.server.class:                DOH\InfraBundle\Form\Type\ServerType
  doh_infra.form.type.server_spec_sheet.class:     DOH\InfraBundle\Form\Type\ServerSpecSheetType
  doh_infra.form.type.server_disk_partition.class: DOH\InfraBundle\Form\Type\DiskPartitionType
  doh_infra.form.type.server_nic.class:            DOH\InfraBundle\Form\Type\NicType
  doh_infra.keyboard_control_extension.class:      DOH\InfraBundle\DependencyInjection\KeyboardControlExtension

services:

  doh_infra.form.type.server:
    class: %doh_infra.form.type.server.class%
    tags:
      - { name: form.type, alias: doh_infra_server }

  doh_infra.form.type.server_spec_sheet:
    class: %doh_infra.form.type.server_spec_sheet.class%
    tags:
      - { name: form.type, alias: doh_infra_server_spec_sheet }

  doh_infra.form.type.server_disk_partition:
    class: %doh_infra.form.type.server_disk_partition.class%
    tags:
      - { name: form.type, alias: doh_infra_server_disk_partition }

  doh_infra.form.type.server_nic:
    class: %doh_infra.form.type.server_nic.class%
    tags:
      - { name: form.type, alias: doh_infra_server_nic }

  doh_infra.keyboard_control_extension:
    class: %doh_infra.keyboard_control_extension.class%
    arguments: [@router]
    tags:
      - { name: doh_main.keyboard_control.extension }
